[package]
name = "rboss"
version = "0.1.0"
edition = "2021"
authors = ["Yangyang Li"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package."*"]
opt-level = 3 # Compile dependencies with optimizations on even in debug mode.

[profile.no-opt]
inherits = "dev"
opt-level = 0

[profile.profiling]
inherits = "release"
debug = true
strip = false

[profile.release]
debug = 0
strip = "symbols"
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.4.7", features = ["wrap_help", "derive"] }
clap-verbosity-flag = "2.1.0"
env_logger = "0.10"
human-panic = "1.2.1"
indicatif = "0.17"
log = "0.4"

noodles-bam = "0.49.0"
noodles-bgzf = "0.25"
noodles-sam = "0.46"
