[package]
name = "rboss"
version = "0.1.0"
edition = "2021"
authors = ["Yangyang Li"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.dev.package."*"]
opt-level = 3 # Compile dependencies with optimizations on even in debug mode.

[profile.no-opt]
inherits = "dev"
opt-level = 0

[profile.profiling]
inherits = "release"
debug = true
strip = false

[dependencies]
clap = { version = "4.4.7", features = ["wrap_help", "derive"] }
